import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import PersonsList from '@/components/PersonsList'

export default function Home() {
  return (
    <>
      <Head>
        <title>Práctica Next13 - Devocamp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <PersonsList />
        <Footer />
      </main>
    </>
  )
}
